// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {reader} from '../models';
import {state} from '../models';
import {main} from '../models';

export function AddBookmark(arg1:string,arg2:number):Promise<void>;

export function DeleteBookmark(arg1:number):Promise<void>;

export function GoToBookmark(arg1:number):Promise<reader.Page>;

export function JumpToOffset(arg1:number):Promise<reader.Page>;

export function JumpToPercent(arg1:number):Promise<reader.Page>;

export function ListBookmarks():Promise<Array<state.Bookmark>>;

export function ListFolderFiles(arg1:string):Promise<Array<main.FolderFile>>;

export function NextPage(arg1:number):Promise<reader.Page>;

export function OpenFile(arg1:string,arg2:string,arg3:number):Promise<main.OpenResult>;

export function ReadAroundOffset(arg1:number,arg2:number,arg3:number):Promise<reader.PageWindow>;

export function ReadNextPage(arg1:number):Promise<reader.Page>;

export function ReadPage(arg1:number):Promise<reader.Page>;

export function ReadPreviousPage(arg1:number):Promise<reader.Page>;

export function SaveProgress(arg1:number):Promise<void>;

export function SearchForward(arg1:number,arg2:string):Promise<main.SearchPageResult>;

export function SearchHitPage(arg1:number,arg2:number):Promise<main.SearchPageResult>;

export function SearchHitPageByIndex(arg1:string,arg2:number):Promise<main.SearchPageResult>;

export function SearchHitPreviews(arg1:string,arg2:number,arg3:number):Promise<reader.SearchHitPreviewPage>;

export function SearchStats(arg1:string,arg2:number):Promise<reader.SearchSummary>;

export function SelectFile():Promise<string>;

export function SelectFolder():Promise<string>;

export function SetLanguage(arg1:string):Promise<void>;

export function StartSearch(arg1:string):Promise<reader.SearchSessionSummary>;
