// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBookmark(arg1, arg2) {
  return window['go']['main']['App']['AddBookmark'](arg1, arg2);
}

export function DeleteBookmark(arg1) {
  return window['go']['main']['App']['DeleteBookmark'](arg1);
}

export function GoToBookmark(arg1) {
  return window['go']['main']['App']['GoToBookmark'](arg1);
}

export function JumpToOffset(arg1) {
  return window['go']['main']['App']['JumpToOffset'](arg1);
}

export function JumpToPercent(arg1) {
  return window['go']['main']['App']['JumpToPercent'](arg1);
}

export function ListBookmarks() {
  return window['go']['main']['App']['ListBookmarks']();
}

export function ListFolderFiles(arg1) {
  return window['go']['main']['App']['ListFolderFiles'](arg1);
}

export function NextPage(arg1) {
  return window['go']['main']['App']['NextPage'](arg1);
}

export function OpenFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenFile'](arg1, arg2, arg3);
}

export function ReadAroundOffset(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadAroundOffset'](arg1, arg2, arg3);
}

export function ReadNextPage(arg1) {
  return window['go']['main']['App']['ReadNextPage'](arg1);
}

export function ReadPage(arg1) {
  return window['go']['main']['App']['ReadPage'](arg1);
}

export function ReadPreviousPage(arg1) {
  return window['go']['main']['App']['ReadPreviousPage'](arg1);
}

export function SaveProgress(arg1) {
  return window['go']['main']['App']['SaveProgress'](arg1);
}

export function SearchForward(arg1, arg2) {
  return window['go']['main']['App']['SearchForward'](arg1, arg2);
}

export function SearchHitPage(arg1, arg2) {
  return window['go']['main']['App']['SearchHitPage'](arg1, arg2);
}

export function SearchHitPageByIndex(arg1, arg2) {
  return window['go']['main']['App']['SearchHitPageByIndex'](arg1, arg2);
}

export function SearchHitPreviews(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchHitPreviews'](arg1, arg2, arg3);
}

export function SearchStats(arg1, arg2) {
  return window['go']['main']['App']['SearchStats'](arg1, arg2);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function StartSearch(arg1) {
  return window['go']['main']['App']['StartSearch'](arg1);
}
